PlateformeDesJeunesV7/Controllers/ComptabiliteController.cs
using Domain.Entities;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Repository.IRepositories;
using Service.IService;

namespace Web.Controllers
{
#nullable disable
    [Authorize(Roles = "Comptable, Admin")]
    public class ComptabiliteController : Controller
    {
        private readonly IComptabiliteService _comptabiliteService;
        private readonly IExerciceRepository _exerciceRepository;

        public ComptabiliteController(IComptabiliteService comptabiliteService, IExerciceRepository exerciceRepository)
        {
            _comptabiliteService = comptabiliteService;
            _exerciceRepository = exerciceRepository;
        }

        public async Task<IActionResult> Exercices(int ChapitreId, double MontantTotale, string Date, int Exercice)
        {
            if (!string.IsNullOrEmpty(Date) || string.IsNullOrEmpty(Date))
            {
                ViewData["Date"] = Date;
                return View(await _comptabiliteService.GetListChapitres(ChapitreId, MontantTotale, Date, Exercice));
            }
            return View(new List<Chapitre>());
        }

        public async Task<IActionResult> Chapitres(int ChapitreId, double MontantTotale, string Date, int Exercice)
        {
            ViewBag.Chapitres = new SelectList(await _comptabiliteService.GetListChapitres(), "ChapitreID", "ChapitreTitle");
            if(ChapitreId != 0 ||  MontantTotale != 0 || !string.IsNullOrEmpty(Date))
            {
                ViewData["ChapitreId"] = ChapitreId;
                ViewData["MontantTotale"] = MontantTotale;
                ViewData["Date"] = Date;
                return View(await _comptabiliteService.GetListChapitres(ChapitreId, MontantTotale, Date, Exercice));
            }
            return View(new List<Chapitre>());
        }

        public async Task<IActionResult> Financements(int Type, string Candidat, string NumeroCheque, string Beneficiaire, double Montant, string SearchDate, string SearchDateO)
        {
            if (Type != 0 || !string.IsNullOrEmpty(Candidat) || !string.IsNullOrEmpty(NumeroCheque) ||
            !string.IsNullOrEmpty(Beneficiaire) || Montant != 0.0 || !string.IsNullOrEmpty(SearchDate) ||
            !string.IsNullOrEmpty(SearchDateO))
            {
                ViewData["Candidat"] = Candidat;
                ViewData["NumeroCheque"] = NumeroCheque;
                ViewData["Beneficiaire"] = Beneficiaire;
                ViewData["Montant"] = Montant;
                ViewData["CurrentFilterD"] = SearchDate;
                ViewData["CurrentFilterDO"] = SearchDateO;
                ViewData["Type"] = Type;
                return View(await _comptabiliteService.GetListFinancement(Type, Candidat, NumeroCheque, Beneficiaire, Montant, SearchDate, SearchDateO));
            }
            return View(new List<Financement>());
        }

        public async Task<IActionResult> Fonctionnements(int ChapitreId, string NuméroCheque, string Beneficiaire, double Montant, string SearchDate, string SearchDateO)
        {
            ViewBag.Chapitres = new SelectList(await _comptabiliteService.GetListChapitres(), "ChapitreID", "ChapitreTitle");

            if (ChapitreId != 0 || !string.IsNullOrEmpty(NuméroCheque) ||
    !string.IsNullOrEmpty(Beneficiaire) || Montant != 0.0 ||
    !string.IsNullOrEmpty(SearchDate) || !string.IsNullOrEmpty(SearchDateO))
            {
                //Envoyer vers ma select list les chapitres
                ViewBag.Chapitres = new SelectList(await _comptabiliteService.GetListChapitres(), "ChapitreID", "ChapitreTitle");

                ViewData["ChapitreId"] = ChapitreId;
                ViewData["NuméroCheque"] = NuméroCheque;
                ViewData["Beneficiaire"] = Beneficiaire;
                ViewData["Montant"] = Montant;
                ViewData["CurrentFilterD"] = SearchDate;
                ViewData["CurrentFilterDO"] = SearchDateO;
                return View(await _comptabiliteService.GetListFonctionnement(ChapitreId, NuméroCheque, Beneficiaire, Montant, SearchDate, SearchDateO));
            }
            return View(new List<Fonctionnement>());
        }

        //[Authorize(Roles = "Comptable")]
        public async Task<IActionResult> Add()
        {
            //Envoyer vers ma select list les chapitres
            ViewBag.Chapitres = new SelectList(await _comptabiliteService.GetListChapitres(), "ChapitreID", "ChapitreTitle");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(ComptabiliteModel model)
        {
            if (model.Financement != null)
            {
                await _comptabiliteService.AddFinancement(model.Financement);
                return RedirectToAction("Financements");
            }
            else
            {
                await _comptabiliteService.AddFonctionnement(model.Fonctionnement);
                return RedirectToAction("Fonctionnements");
            }
        }


        [Authorize(Roles = "Admin")]
        public IActionResult AddChapitre(string success)
        {
            if (success != null)
            {
                ViewBag.Success = "1";
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddChapitreAsync(Chapitre chapitre)
        {
            await _comptabiliteService.AddChapitreByAdmin(chapitre);
            return RedirectToAction("AddChapitre", new { success = "1" });
        }

        [HttpGet]
        public async Task<IActionResult> RemoveFonctionnement(int id)
        {
            await _comptabiliteService.DeleteFonctionnement(id);
            return RedirectToAction("Fonctionnements");
        }

        [HttpGet]
        public async Task<IActionResult> RemoveFinancement(int id)
        {
            await _comptabiliteService.DeleteFinancement(id);
            return RedirectToAction("Financements");
        }

        [HttpGet]
        public async Task<IActionResult> RemoveChapitre(int id)
        {
            await _comptabiliteService.DeleteChapitreAndFonctionnementsRelative(id);
            return RedirectToAction("Chapitres");
        }

        [HttpGet]
        public async Task<IActionResult> UpdateFonctionnement(int id)
        {
            //Envoyer vers ma select list les chapitres
            ViewBag.Chapitres = new SelectList(await _comptabiliteService.GetListChapitres(), "ChapitreID", "ChapitreTitle");
            return View(await _comptabiliteService.GetFonctionnementById(id));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateFinancement(int id)
        {
            return View(await _comptabiliteService.GetFinancementById(id));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateChapitre(int id)
        {
            return View(await _comptabiliteService.GetChapitreById(id));
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFonctionnement(Fonctionnement model)
        {
            await _comptabiliteService.UpdateFonctionnement(model);
            return RedirectToAction("Fonctionnements");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFinancement(Financement model)
        {
            await _comptabiliteService.UpdateFinancement(model);
            return RedirectToAction("Financements");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateChapitre(Chapitre chapitre)
        {
            await _comptabiliteService.UpdateChapitre(chapitre);
            return RedirectToAction("Chapitres");
        }

        //CRUD Budget financement
        public async Task<IActionResult> BudgetFinancement(string DateBudget, string Emetteur, string NumeroCheque)
        {
            return View(await _comptabiliteService.BudgetFinancements(DateBudget, Emetteur, NumeroCheque));
        }

        public IActionResult AddBudgetFinancement()
        {
            return View();
        }

        public async Task<IActionResult> UpdateBudgetFinancement(int id)
        {
            return View(await _comptabiliteService.GetBudgetFinancementById(id));
        }

        [HttpPost]
        public async Task<IActionResult> AddBudgetFinancement(BudgetFinancement model)
        {
            await _comptabiliteService.AddBudgetFinancement(model);
            return RedirectToAction("BudgetFinancement");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBudgetFinancement(BudgetFinancement model)
        {
            await _comptabiliteService.UpdateBudgetFinancement(model);
            return RedirectToAction("BudgetFinancement");
        }

        [HttpGet]
        public async Task<IActionResult> RemoveBudgetFinancement(int id)
        {
            await _comptabiliteService.DeleteBudgetFinancement(id);
            return RedirectToAction("BudgetFinancement");
        }

        //CRUD Budget fonctionnement
        public async Task<IActionResult> BudgetFonctionnement(string DateBudget, string Emetteur, string NumeroCheque)
        {
            return View(await _comptabiliteService.BudgetFonctionnements(DateBudget, Emetteur, NumeroCheque));
        }
        public IActionResult AddBudgetFonctionnement()
        {
            return View();
        }
        public async Task<IActionResult> UpdateBudgetFonctionnement(int id)
        {
            return View(await _comptabiliteService.GetBudgetFonctionnementById(id));
        }


        [HttpPost]
        public async Task<IActionResult> AddBudgetFonctionnement(BudgetFonctionnement model)
        {
            await _comptabiliteService.AddBudgetFonctionnement(model);
            return RedirectToAction("BudgetFonctionnement");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateBudgetFonctionnement(BudgetFonctionnement model)
        {

PlateformeDesJeunesV7/Views/Comptabilite/AddBudgetFinancement.cshtml
@model Domain.Entities.BudgetFinancement

@{
    ViewData["Title"] = "Créer un Budget de Financement";
}

@{
    Layout = "_LayoutDashboard";
}

<div class="card mb-4">
    <div style="display:flex;justify-content:space-between;">
        <div class="card-header">
            <h3 class="mb-0">Saisie d'un Budget de Financement</h3>
            <span>
                Saisissez les informations ci-dessous.
            </span>
        </div>
    </div>
    <!-- Card body -->
    <div class="card-body">
        <form asp-action="AddBudgetFinancement" method="post" class="col-xl-6 col-lg-6 col-md-6 col-12 mb-2" style="margin: auto;margin-top:30px;" id="CreateBudgetForm">
            <div class="form-group">
                <label class="control-label">Date du Budget</label>
                <input required class="form-control" asp-for="DateBudget" type="date" />
            </div>
            <div class="form-group">
                <label class="control-label">Montant du Budget</label>
                <input required class="form-control" asp-for="MontantBudget" type="number" step="0.01" />
            </div>
            <div class="form-group">
                <label class="control-label">Émetteur du Budget</label>
                <input required class="form-control" asp-for="EmetteurBudget" />
            </div>
            <div class="form-group">
                <label class="control-label">Numéro de Chèque (optionnel)</label>
                <input class="form-control" asp-for="NuméroCheque" />
            </div>
            <div class="form-group">
                <input type="submit" value="Créer le Budget" class="btn btn-primary" />
                <a style="margin-left:15px;" asp-action="BudgetFinancement">Retour</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <!-- Ajoutez ici des scripts JavaScript personnalisés si nécessaire -->
}

PlateformeDesJeunesV7/Views/Comptabilite/BudgetFinancement.cshtml
@model IEnumerable<Domain.Entities.BudgetFinancement>
@using System.Globalization
@{
    ViewData["Title"] = "Liste des Budgets de Financement";
    var nfi = (NumberFormatInfo)CultureInfo.InvariantCulture.NumberFormat.Clone();
    nfi.NumberGroupSeparator = " ";
}

@{
    Layout = "_LayoutDashboard";
}
<div class="card mb-4">
    <div style="display:flex;justify-content:space-between;">
        <div class="card-header">
            <h3 class="mb-0">Budgets de Financement</h3>
            <span>
                Utilisez les filtres pour rechercher vos budgets de financement.
            </span>
        </div>
        <div class="card-header">
            <a type="button" class="btn btn-info" asp-action="AddBudgetFinancement">Ajouter un budget de financement</a>
        </div>
    </div>


        <div class="card-body mt-3">
            <!-- Form de recherche -->
            <form class="form-row" asp-action="BudgetFinancement" asp-controller="Comptabilite" method="get">
                <div class="col-lg-4 col-md-4 col-12 mb-2">
                    <input name="DateBudget" value="@ViewData["DateBudget"]" type="text" class="form-control flatpickr" placeholder="Date du Budget" />
                </div>
                <div class="col-lg-4 col-md-4 col-12 mb-2">
                    <input name="Emetteur" value="@ViewData["Emetteur"]" type="text" class="form-control" placeholder="Émetteur du Budget" />
                </div>
                <div class="col-lg-4 col-md-4 col-12 mb-2">
                    <input name="NumeroCheque" value="@ViewData["NumeroCheque"]" type="text" class="form-control" placeholder="Numéro de Chèque" />
                </div>
                <div class="col-lg-12 col-md-12 col-12 mb-2">
                    <button type="submit" class="btn btn-outline-info me-2">Rechercher</button>
                    <a asp-action="BudgetFinancement" asp-controller="Comptabilite" type="button" class="btn btn-outline-primary">Réinitialiser</a>
                </div>
            </form>
        </div>
    </div>
    <!-- Card body -->
    <div class="card-body">
        @if (Model != null && Model.Any())
        {
        <div class="card mb-4">
            <!-- Table -->
            <div class="table-responsive">
                <table class="table mb-0 table-hover table-centered text-nowrap">
                    <thead class="table-light">
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col" class="border-0">Date du Budget</th>
                    <th scope="col" class="border-0">Montant du Budget</th>
                    <th scope="col" class="border-0">Émetteur du Budget</th>
                    <th scope="col" class="border-0">Numéro de Chèque</th>
                    <th scope="col" class="border-0">Action</th>
                </tr>
            </thead>
            <tbody>
                    @foreach (var budget in Model)
                    {
                        <tr>
                            <td class="border-top-0">@budget.BudgetFinancementID</td>
                            <td class="border-top-0">@budget.DateBudget.ToString("dd/MM/yyyy")</td>
                            <td class="border-top-0">@budget.MontantBudget.ToString("#,##0.00", nfi)</td>
                            <td class="border-top-0">@budget.EmetteurBudget</td>
                            <td class="border-top-0">@budget.NuméroCheque</td>
                            <td class="border-top-0">
                                <a asp-action="UpdateBudgetFinancement" asp-route-id="@budget.BudgetFinancementID">
                                    <i class="fe fe-edit dropdown-item-icon"></i>
                                </a>
                                <a style="cursor:pointer;" id="@budget.BudgetFinancementID" onclick="confirmDelete(this)">
                                    <i class="fe fe-trash dropdown-item-icon"></i>
                                </a>
                            </td>
                        </tr>
                    }
            </tbody>
        </table>
        </div>
        </div>
        }
        else
        {
            <p>Aucun budget de financement n'a été enregistré.</p>
        }
    </div>
@section Scripts {
    <script>
        function confirmDelete(button) {
            var budgetID = button.id;
            alertify.confirm('Confirmation de suppression', 'Êtes-vous sûr de vouloir supprimer cet élément ?', function () {
                // Redirigez vers l'action de suppression avec l'ID du budget
                window.location.href = '@Url.Action("RemoveBudgetFinancement", "Comptabilite")' + '/' + budgetID;
            }, function () {
                // L'utilisateur a annulé la suppression, aucune action nécessaire
            });
        }
    </script>
}

PlateformeDesJeunesV7/Views/Comptabilite/BudgetFonctionnement.cshtml
@model List<Domain.Entities.BudgetFonctionnement>
@using System.Globalization
@{
    Layout = "_LayoutDashboard";
    var nfi = (NumberFormatInfo)CultureInfo.InvariantCulture.NumberFormat.Clone();
    nfi.NumberGroupSeparator = " ";
}

<style>
    .disabled {
    }
</style>

<div class="card mb-4">
    <div style="display:flex;justify-content:space-between;">
        <div class="card-header">
            <h3 class="mb-0">Budgets de Fonctionnement</h3>
            <span>
                Utilisez les filtres pour rechercher vos budgets de fonctionnement.
            </span>
        </div>
        <div class="card-header">
            <a type="button" class="btn btn-info" asp-action="AddBudgetFonctionnement">Ajouter un budget de fonctionnement</a>
        </div>
    </div>
    <!-- Card header -->
    <!-- Card body -->
    <div class="card-body mt-3">
        <!-- Form de recherche -->
        <form class="form-row" asp-action="BudgetFonctionnement" asp-controller="Comptabilite" method="get">
            <div class="col-lg-4 col-md-4 col-12 mb-2">
                <input name="DateBudget" value="@ViewData["DateBudget"]" type="text" class="form-control flatpickr" placeholder="Date du Budget" />
            </div>
            <div class="col-lg-4 col-md-4 col-12 mb-2">
                <input name="Emetteur" value="@ViewData["Emetteur"]" type="text" class="form-control" placeholder="Émetteur du Budget" />
            </div>
            <div class="col-lg-4 col-md-4 col-12 mb-2">
                <input name="NumeroCheque" value="@ViewData["NumeroCheque"]" type="text" class="form-control" placeholder="Numéro de Chèque" />
            </div>
            <div class="col-lg-12 col-md-12 col-12 mb-2">
                <button type="submit" class="btn btn-outline-info me-2">Rechercher</button>
                <a asp-action="BudgetFonctionnement" asp-controller="Comptabilite" type="button" class="btn btn-outline-primary">Réinitialiser</a>
            </div>
        </form>
    </div>
</div>

@if (Model != null && Model.Any())
{
    <div class="card mb-4">
    <!-- Table -->
    <div class="table-responsive">
            <table class="table mb-0 table-hover table-centered text-nowrap">
                <thead class="table-light">
                <tr>
                    <th scope="col" class="border-0">#</th>
                    <th scope="col" class="border-0">Date du Budget</th>
                    <th scope="col" class="border-0">Montant du Budget</th>
                    <th scope="col" class="border-0">Émetteur du Budget</th>
                    <th scope="col" class="border-0">Numéro de Chèque</th>
                    <th scope="col" class="border-0">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var budget in Model)
                {
                    <tr>
                        <td>@budget.BudgetFonctionnementID</td>
                        <td>@budget.DateBudget.ToString("dd/MM/yyyy")</td>
                        <td>@budget.MontantBudget.ToString("#,##0.00", nfi)</td>
                        <td>@budget.EmetteurBudget</td>
                        <td>@budget.NuméroCheque</td>
                        <td>
                            <a asp-action="UpdateBudgetFonctionnement" asp-route-id="@budget.BudgetFonctionnementID">
                                <i class="fe fe-edit dropdown-item-icon"></i>
                            </a>
                            <a style="cursor:pointer;" id="@budget.BudgetFonctionnementID" onclick="confirmDelete(this)">
                                <i class="fe fe-trash dropdown-item-icon"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    </div>
}
else
{
    <p>Aucun budget de fonctionnement n'a été enregistré.</p>
}

@section Scripts {
    <script>
        function confirmDelete(button) {
            var budgetID = button.id;
            alertify.confirm('Confirmation de suppression', 'Êtes-vous sûr de vouloir supprimer ce budget de fonctionnement ?', function () {
                window.location.href = '@Url.Action("RemoveBudgetFonctionnement", "Comptabilite")' + '/' + budgetID;
            }, function () {
                // Annuler la suppression
            });
        }
    </script>
}

PlateformeDesJeunesV7/Views/Comptabilite/Chapitres.cshtml
@model List<Chapitre>
@using System.Globalization
@{
    Layout = "_LayoutDashboard";
    var nfi = (NumberFormatInfo)CultureInfo.InvariantCulture.NumberFormat.Clone();
    nfi.NumberGroupSeparator = " ";
}
<style>
    .disabled {
    }

    #tableauChapitres th {
        width: 25%;
    }

</style>
<div class="card mb-4">
    <div style="display:flex;justify-content:space-between;">
        <div class="card-header">
            <h3 class="mb-0">Chapitres</h3>
            <span>
                Utiliser les filtres pour rechercher.
            </span>
        </div>
        <div class="card-header">
            @if (User.IsInRole("Admin"))
            {
                <a type="button" class="btn btn-info" asp-controller="Comptabilite" asp-action="AddChapitre">Ajouter un nouveau chapitre</a>
            }

            <a type="button" class="btn btn-primary" asp-controller="Comptabilite" asp-action="Add">Nouvelle saisie</a>

        </div>
    </div>
    <!-- Card header -->
    <!-- Card body -->
    <div class="card-body">
        <!-- Form -->
        <form class="form-row mt-3" asp-action="Chapitres" asp-controller="Comptabilite" method="get">
            <div class="col-lg-6 mb-2 col-md-6 col-12 ">
                <select name="ChapitreId" value="@ViewData["ChapitreId"]" class="selectpicker" data-width="100%" asp-items="ViewBag.Chapitres">
                    <option value="" selected>--- Chapitres ---</option>
                </select>
            </div>

            <div class="col-lg-6 mb-2 col-md-6 col-12  ">
                <input name="MontantTotale" id="MontantTotale" type="number" class="form-control" placeholder="Montant" />
            </div>
            <div class="col-lg-6 col-md-6 col-12 mb-2">
                <div class="w-md-50">
                    <input name="DateCreation" id="Date" value="@ViewData["Date"]" type="text" class="form-control flatpickr" placeholder="Date">
                </div>
            </div>
            <div class="col-lg-12 col-md-12 col-12 mb-2" style="text-align:right!important;">
                <button type="submit" class="btn btn-outline-info me-2">Rechercher</button>
                <a asp-action="Chapitres" type="button" class="btn btn-outline-primary">Initialiser</a>
            </div>
        </form>
    </div>

</div>
<!-- Card header -->
<div class="card-header border-bottom-0">
    <h3 class="mb-0">Les chapitres</h3>
    <span>
        Cliquer sur détails pour visualiser les fonctionnements.
    </span>
</div>
<div class="text-center">
@if (Model != null)
{
    @foreach (var item in Model)
    {
        //Index du foreach
        var index = Model.IndexOf(item);

        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="table-responsive">
                        <table class="table mb-0 text-nowrap table-hover">
                            <thead class="table-light">
                                <tr>
                                        <th scope="col">Chapitre @(index + 1)</th>
                                        <th scope="col">Montant totale</th>
                                        <th scope="col">Montant restant</th>
                                        <th scope="col">Montant utilisé</th>
                                        <th scope="col">Date</th>
                                        <th scope="col">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <a href="#" class="text-inherit">@item.ChapitreTitle</a>
                                    </td>
                                    <td>
                                        @item.MontantTotale.ToString("#,##0.00", nfi)
                                    </td>
                                    <td>
                                            @{
                                                var MontantRestant = (item.MontantTotale - item.Fonctionnements.Sum(c => c.Montant)).GetValueOrDefault();
                                        }
                                            @MontantRestant.ToString("#,##0.00", nfi)
                                    </td>
                                        <td>
                                            @((item.MontantTotale - MontantRestant).ToString("#,##0.00", nfi))
                                        </td>
                                    <td>
                                        @item.DateCreation.ToString("dd/MM/yyyy", nfi)
                                    </td>
                                    <td>
                                        @if (item.Fonctionnements.Count > 0)
                                        {
                                            <a data-toggle="collapse" href="#collapseExample@(index)" role="button" aria-expanded="false" aria-controls="collapseExample" onclick="toggleIcon(this)"> <i class="fas fa-chevron-down dropdown-item-icon"></i></a>
                                        }
                                        <a asp-action="UpdateChapitre" asp-controller="Comptabilite" asp-route-id="@item.ChapitreID"><i class="fe fe-edit dropdown-item-icon"></i></a>
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <a style="cursor:pointer;" id="@item.ChapitreID" onclick="confirm(this)"><i class="fe fe-trash dropdown-item-icon"></i></a>
                                        }
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>
        
            <!-- Table 2 ------------------------------------------------------------------------------------------------- -->
            <div class="collapse" id="collapseExample@(index)">
                <div class="row mt-0 mt-md-4">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class="table mb-0 text-nowrap table-hover table-centered">
                                <thead class="table-light">
                                    <tr>
                                        <th>Numéro de chèque</th>
                                        <th>Bénéficiare</th>
                                        <th>Montant</th>
                                    <th>Date</th>
                                    <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var fonctionnement in item.Fonctionnements)
                                    {
                                        <tr>
                                            <td>
                                                @fonctionnement.NuméroCheque
                                            </td>
                                            <td>
                                                @fonctionnement.Beneficiaire
                                            </td>

                                            <td>
                                                @fonctionnement.Montant.GetValueOrDefault().ToString("#,##0.00", nfi)
                                            </td>
                                            <td>
                                            @(fonctionnement.Date == null ? "__" : fonctionnement.Date.GetValueOrDefault().ToString("dd/MM/yyyy"))
                                            </td>
                                            <td>
                                            <a asp-action="UpdateFonctionnement" asp-controller="Comptabilite" asp-route-id="@fonctionnement.FonctionnementID"><i class="fe fe-edit dropdown-item-icon"></i></a>
                                            <a style="cursor:pointer;" id="@fonctionnement.FonctionnementID" onclick="confirm(this)"><i class="fe fe-trash dropdown-item-icon"></i></a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
    }
}
</div>
<div style="margin-bottom:20vh;"></div>
@section Scripts {
    <script>
        function confirm(idButton) {
            var pageURL = $(location).attr("href");
            alertify.confirm('Confirmation de suppression', 'Est-te vous sûr de vouloir supprimer cet élement ?', function () { window.location.replace("@(Url.Action("RemoveChapitre"))" + "/" + idButton.id) }
                , function () { /*alertify.error('Cancel')*/ });
        }

        function toggleIcon(link) {
            var icon = link.querySelector('i');
            if (icon.classList.contains('fa-chevron-down')) {
                icon.classList.remove('fa-chevron-down');
                icon.classList.add('fa-chevron-up');
            } else {
                icon.classList.remove('fa-chevron-up');
                icon.classList.add('fa-chevron-down');
            }
        }

    </script>

}