PlateformeDesJeunesV7/Controllers/ComptabiliteController.cs
using Domain.Entities;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Repository.IRepositories;
using Service.IService;

namespace Web.Controllers
{
#nullable disable
    [Authorize(Roles = "Comptable, Admin")]
    public class ComptabiliteController : Controller
    {
        private readonly IComptabiliteService _comptabiliteService;
        private readonly IExerciceRepository _exerciceRepository;

        public ComptabiliteController(IComptabiliteService comptabiliteService, IExerciceRepository exerciceRepository)
        {
            _comptabiliteService = comptabiliteService;
            _exerciceRepository = exerciceRepository;
        }

        public async Task<IActionResult> Exercices(int ChapitreId, double MontantTotale, string Date, int Exercice)
        {
            if (!string.IsNullOrEmpty(Date) || string.IsNullOrEmpty(Date))
            {
                ViewData["Date"] = Date;
                return View(await _comptabiliteService.GetListChapitres(ChapitreId, MontantTotale, Date, Exercice));
            }
            return View(new List<Chapitre>());
        }

        public async Task<IActionResult> Chapitres(int ChapitreId, double MontantTotale, string Date, int Exercice)
        {
            ViewBag.Chapitres = new SelectList(await _comptabiliteService.GetListChapitres(), "ChapitreID", "ChapitreTitle");
            if(ChapitreId != 0 ||  MontantTotale != 0 || !string.IsNullOrEmpty(Date))
            {
                ViewData["ChapitreId"] = ChapitreId;
                ViewData["MontantTotale"] = MontantTotale;
                ViewData["Date"] = Date;
                return View(await _comptabiliteService.GetListChapitres(ChapitreId, MontantTotale, Date, Exercice));
            }
            return View(new List<Chapitre>());
        }

        public async Task<IActionResult> Financements(int Type, string Candidat, string NumeroCheque, string Beneficiaire, double Montant, string SearchDate, string SearchDateO)
        {
            if (Type != 0 || !string.IsNullOrEmpty(Candidat) || !string.IsNullOrEmpty(NumeroCheque) ||
            !string.IsNullOrEmpty(Beneficiaire) || Montant != 0.0 || !string.IsNullOrEmpty(SearchDate) ||
            !string.IsNullOrEmpty(SearchDateO))
            {
                ViewData["Candidat"] = Candidat;
                ViewData["NumeroCheque"] = NumeroCheque;
                ViewData["Beneficiaire"] = Beneficiaire;
                ViewData["Montant"] = Montant;
                ViewData["CurrentFilterD"] = SearchDate;
                ViewData["CurrentFilterDO"] = SearchDateO;
                ViewData["Type"] = Type;
                return View(await _comptabiliteService.GetListFinancement(Type, Candidat, NumeroCheque, Beneficiaire, Montant, SearchDate, SearchDateO));
            }
            return View(new List<Financement>());
        }

        public async Task<IActionResult> Fonctionnements(int ChapitreId, string NuméroCheque, string Beneficiaire, double Montant, string SearchDate, string SearchDateO)
        {
            ViewBag.Chapitres = new SelectList(await _comptabiliteService.GetListChapitres(), "ChapitreID", "ChapitreTitle");

            if (ChapitreId != 0 || !string.IsNullOrEmpty(NuméroCheque) ||
    !string.IsNullOrEmpty(Beneficiaire) || Montant != 0.0 ||
    !string.IsNullOrEmpty(SearchDate) || !string.IsNullOrEmpty(SearchDateO))
            {
                //Envoyer vers ma select list les chapitres
                ViewBag.Chapitres = new SelectList(await _comptabiliteService.GetListChapitres(), "ChapitreID", "ChapitreTitle");

                ViewData["ChapitreId"] = ChapitreId;
                ViewData["NuméroCheque"] = NuméroCheque;
                ViewData["Beneficiaire"] = Beneficiaire;
                ViewData["Montant"] = Montant;
                ViewData["CurrentFilterD"] = SearchDate;
                ViewData["CurrentFilterDO"] = SearchDateO;
                return View(await _comptabiliteService.GetListFonctionnement(ChapitreId, NuméroCheque, Beneficiaire, Montant, SearchDate, SearchDateO));
            }
            return View(new List<Fonctionnement>());
        }

        //[Authorize(Roles = "Comptable")]
        public async Task<IActionResult> Add()
        {
            //Envoyer vers ma select list les chapitres
            ViewBag.Chapitres = new SelectList(await _comptabiliteService.GetListChapitres(), "ChapitreID", "ChapitreTitle");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(ComptabiliteModel model)
        {
            if (model.Financement != null)
            {
                await _comptabiliteService.AddFinancement(model.Financement);
                return RedirectToAction("Financements");
            }
            else
            {
                await _comptabiliteService.AddFonctionnement(model.Fonctionnement);
                return RedirectToAction("Fonctionnements");
            }
        }


        [Authorize(Roles = "Admin")]
        public IActionResult AddChapitre(string success)
        {
            if (success != null)
            {
                ViewBag.Success = "1";
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddChapitreAsync(Chapitre chapitre)
        {
            await _comptabiliteService.AddChapitreByAdmin(chapitre);
            return RedirectToAction("AddChapitre", new { success = "1" });
        }

        [HttpGet]
        public async Task<IActionResult> RemoveFonctionnement(int id)
        {
            await _comptabiliteService.DeleteFonctionnement(id);
            return RedirectToAction("Fonctionnements");
        }

        [HttpGet]
        public async Task<IActionResult> RemoveFinancement(int id)
        {
            await _comptabiliteService.DeleteFinancement(id);
            return RedirectToAction("Financements");
        }

        [HttpGet]
        public async Task<IActionResult> RemoveChapitre(int id)
        {
            await _comptabiliteService.DeleteChapitreAndFonctionnementsRelative(id);
            return RedirectToAction("Chapitres");
        }

        [HttpGet]
        public async Task<IActionResult> UpdateFonctionnement(int id)
        {
            //Envoyer vers ma select list les chapitres
            ViewBag.Chapitres = new SelectList(await _comptabiliteService.GetListChapitres(), "ChapitreID", "ChapitreTitle");
            return View(await _comptabiliteService.GetFonctionnementById(id));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateFinancement(int id)
        {
            return View(await _comptabiliteService.GetFinancementById(id));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateChapitre(int id)
        {
            return View(await _comptabiliteService.GetChapitreById(id));
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFonctionnement(Fonctionnement model)
        {
            await _comptabiliteService.UpdateFonctionnement(model);
            return RedirectToAction("Fonctionnements");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateFinancement(Financement model)
        {
            await _comptabiliteService.UpdateFinancement(model);
            return RedirectToAction("Financements");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateChapitre(Chapitre chapitre)
        {
            await _comptabiliteService.UpdateChapitre(chapitre);
            return RedirectToAction("Chapitres");
        }

        //CRUD Budget financement
        public async Task<IActionResult> BudgetFinancement(string DateBudget, string Emetteur, string NumeroCheque)
        {
            return View(await _comptabiliteService.BudgetFinancements(DateBudget, Emetteur, NumeroCheque));
        }

        public IActionResult AddBudgetFinancement()
        {
            return View();
        }

        public async Task<IActionResult> UpdateBudgetFinancement(int id)
        {
            return View(await _comptabiliteService.GetBudgetFinancementById(id));
        }

        [HttpPost]
        public async Task<IActionResult> AddBudgetFinancement(BudgetFinancement model)
        {
            await _comptabiliteService.AddBudgetFinancement(model);
            return RedirectToAction("BudgetFinancement");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateBudgetFinancement(BudgetFinancement model)
        {
            await _comptabiliteService.UpdateBudgetFinancement(model);
            return RedirectToAction("BudgetFinancement");
        }

        [HttpGet]
        public async Task<IActionResult> RemoveBudgetFinancement(int id)
        {
            await _comptabiliteService.DeleteBudgetFinancement(id);
            return RedirectToAction("BudgetFinancement");
        }

        //CRUD Budget fonctionnement
        public async Task<IActionResult> BudgetFonctionnement(string DateBudget, string Emetteur, string NumeroCheque)
        {
            return View(await _comptabiliteService.BudgetFonctionnements(DateBudget, Emetteur, NumeroCheque));
        }
        public IActionResult AddBudgetFonctionnement()
        {
            return View();
        }
        public async Task<IActionResult> UpdateBudgetFonctionnement(int id)
        {
            return View(await _comptabiliteService.GetBudgetFonctionnementById(id));
        }


        [HttpPost]
        public async Task<IActionResult> AddBudgetFonctionnement(BudgetFonctionnement model)
        {
            await _comptabiliteService.AddBudgetFonctionnement(model);
            return RedirectToAction("BudgetFonctionnement");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateBudgetFonctionnement(BudgetFonctionnement model)
        {

PlateformeDesJeunesV7/Controllers/FormationsController.cs
using Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.IService;

namespace Web.Controllers
{
#nullable disable
    [Authorize(Roles = "Admin, Gestionnaire, HeureJoyeuse, Amideast")]
    public class FormationsController : Controller
    {
        private readonly IFormationService _formationService;

        public FormationsController(IFormationService formationService)
        {
            _formationService = formationService;
        }

        public async Task<IActionResult> Index(int? pageNumber, string Theme, string Animateur, int Duree, string SearchDate, string SearchDateO)
        {
            return View(await _formationService.getFormations(pageNumber, User, Theme, Animateur, Duree, SearchDate, SearchDateO));
        }

        public async Task<IActionResult> Details(int id)
        {
            return View(await _formationService.getFormation(id));
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Add(Formation formation)
        {
            await _formationService.AddFormation(formation);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            return View(await _formationService.getFormation(Id));
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Formation formation)
        {
            await _formationService.Edit(formation);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            await _formationService.Delete(Id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<string> EditAffectation(int formationId, int clientId, bool valide)
        {
            await _formationService.EditAffectation(formationId, clientId, valide);
            return "OK";
        }

        [HttpGet]
        public async Task<IActionResult> Candidats(int FormationID, string Theme, string SearchNom, string SearchPrenom, string SearchDate, string SearchDateO, int? pageNumber, string SearchCIN, string SearchStatut, string OrientationFilter)
        {
            if (FormationID != 0)
            {
                ViewData["FormationID"] = FormationID;
            }

            ViewData["OrientationSortParm"] = OrientationFilter;
            ViewData["Theme"] = Theme;
            ViewData["CINSortParm"] = SearchCIN;
            ViewData["StatutSortParm"] = SearchStatut;
            ViewData["CurrentFilterN"] = SearchNom;
            ViewData["CurrentFilterP"] = SearchPrenom;
            ViewData["CurrentFilterD"] = SearchDate;
            ViewData["CurrentFilterDO"] = SearchDateO;


            return View(await _formationService.getCandidats(FormationID, Theme, SearchNom, SearchPrenom, SearchDate, SearchDateO, pageNumber, SearchCIN, SearchStatut, OrientationFilter, User));
        }
    }
}

PlateformeDesJeunesV7/Controllers/StatistiquesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.IService;

namespace Web.Controllers
{
#nullable disable
    [Authorize(Roles = "Admin")]
    public class StatistiquesController : Controller
    {
        private readonly IStatistiqueService _statistiqueService;

        public StatistiquesController(IStatistiqueService statistiqueService)
        {
            _statistiqueService = statistiqueService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _statistiqueService.GetStatistique());
        }

        public async Task<IActionResult> P2(string PGFilter, string SearchDate, string SearchDateO, int? Cloture_EnCours)
        {
            ViewData["CurrentFilterD"] = SearchDate;
            ViewData["CurrentFilterDO"] = SearchDateO;
            ViewData["PlateformeGestionnaireSortParm"] = PGFilter;
            ViewData["Cloture_EnCours"] = Cloture_EnCours;
            return View(await _statistiqueService.GetStatistique(PGFilter, SearchDate, SearchDateO, Cloture_EnCours));
        }

        public async Task<IActionResult> P3(string DateDu, string DateAu)
        {
            ViewData["DateDu"] = DateDu;
            ViewData["DateAu"] = DateAu;
            return View(await _statistiqueService.StatistiquesComptabilite(DateDu, DateAu));
        }

    }
}

PlateformeDesJeunesV7/Views/Statistiques/Index.cshtml
@model Domain.Models.Statistique;


@{
    ViewBag.Title = "title";
    Layout = "_LayoutDashboard";
}

<div class="container-fluid p-4" style="
    background-color: white;">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <div class="border-bottom pb-4 mb-4 d-lg-flex justify-content-between align-items-center">
                <div>
                    <h1 class="mb-0 h2 font-weight-bold">Dashboard</h1>
                </div>

            </div>
        </div>
    </div>
    <div class="row">
            
            <div class="col-xl-6 col-lg-6 col-md-12 col-12">
              <!-- Card -->
              <div class="card mb-4">
                <!-- Card body -->
                <div class="card-body">
                  <div class="d-flex align-items-center justify-content-between mb-3 lh-1">
                    <div>
                      <span class="font-size-xs text-uppercase font-weight-semi-bold">Total des candidats</span>
                    </div>
                    <div>
                      <a target="_blank" asp-controller="Candidats" asp-action="Index"><span class=" fe fe-book-open font-size-lg text-primary"></span></a>
                    </div>
                  </div>
                  <h2 class="font-weight-bold mb-1">
                    @Model.candidatAcceuilli
                  </h2>
                  @*<span class="text-danger font-weight-semi-bold">120+</span>*@
                  <span class="ml-1 font-weight-medium">Nombre de candidat</span>
                </div>
              </div>
            </div>
            <div class="col-xl-6 col-lg-6 col-md-12 col-12">
              <!-- Card -->
              <div class="card mb-4">
                <!-- Card body -->
                <div class="card-body">
                  <div class="d-flex align-items-center justify-content-between mb-3 lh-1">
                    <div>
                      <span class="font-size-xs text-uppercase font-weight-semi-bold">Nombre de candidat orientée</span>
                    </div>
                    <div>
                            <a target="_blank" asp-controller="Candidats" asp-action="Index" asp-route-OrientationFilter="Orienté"><span class=" fe fe-users font-size-lg text-primary"></span></a>
                    </div>
                  </div>
                  <h2 class="font-weight-bold mb-1">
                    @Model.nombreCandidatAcceuilliEtOriente
                  </h2>
                  @*<span class="text-success font-weight-semi-bold"><i class="fe fe-trending-up mr-1"></i>+1200</span>*@
                  <span class="ml-1 font-weight-medium">Nombre de candidats orientée</span>
                </div>
              </div>
            </div>
        <div class="col-xl-6 col-lg-6 col-md-12 col-12">
            <!-- Card -->
            <div class="card mb-4">
                <!-- Card body -->
                <div class="card-body">
                    <div class="d-flex align-items-center justify-content-between mb-3 lh-1">
                        <div>
                            <span class="font-size-xs text-uppercase font-weight-semi-bold">Nombre de candidat avec status d'orientation Refusé</span>
                        </div>
                        <div>
                            <a target="_blank" asp-controller="Candidats" asp-action="Index" asp-route-OrientationFilter="Refusé"><span class=" fe fe-users font-size-lg text-primary"></span></a>
                        </div>
                    </div>
                    <h2 class="font-weight-bold mb-1">
                        @Model.nombreCandidatRefusé
                    </h2>
                    @*<span class="text-success font-weight-semi-bold"><i class="fe fe-trending-up mr-1"></i>+1200</span>*@
                    <span class="ml-1 font-weight-medium">Nombre de candidats orientée</span>
                </div>
            </div>
        </div>
            <div class="col-xl-6 col-lg-6 col-md-12 col-12">
              <!-- Card -->
              <div class="card mb-4">
                <!-- Card body -->
                <div class="card-body">
                  <div class="d-flex align-items-center justify-content-between mb-3 lh-1">
                    <div>
                      <span class="font-size-xs text-uppercase font-weight-semi-bold">Total des formations</span>
                    </div>
                    <div>
                            <a target="_blank" asp-controller="Formations" asp-action="Index"><span class="fe fe-shopping-bag font-size-lg text-primary"></span></a>
                    </div>
                  </div>
                  <h2 class="font-weight-bold mb-1">
                    @Model.nombreFormation 
                  </h2>
                  @*<span class="text-success font-weight-semi-bold"><i class="fe fe-trending-up mr-1"></i>+20.9$</span>*@
                  <span class="ml-1 font-weight-medium">Nombres de formations</span>
                </div>
              </div>
            </div>
            <div class="col-xl-6 col-lg-6 col-md-12 col-12">
              <!-- Card -->
              <div class="card mb-4">
                <!-- Card body -->
                <div class="card-body">
                  <div class="d-flex align-items-center justify-content-between mb-3 lh-1">
                    <div>
                      <span class="font-size-xs text-uppercase font-weight-semi-bold">Chercheur d'emploit</span>
                    </div>
                    <div>
                            <a target="_blank" asp-controller="Candidats" asp-action="Index" asp-route-SearchStatut="1"><span class=" fe fe-user-check font-size-lg text-primary"></span></a>
                    </div>
                  </div>
                  <h2 class="font-weight-bold mb-1">
                    @Model.nombreChercheurEmploit
                  </h2>
                  @*<span class="text-success font-weight-semi-bold"><i class="fe fe-trending-up mr-1"></i>+200</span>*@
                  <span class="ml-1 font-weight-medium">Nombre de chercheur d'emploit</span>
                </div>
              </div>
            </div>

            <div class="col-xl-6 col-lg-6 col-md-12 col-12">
              <!-- Card -->
              <div class="card mb-4">
                <!-- Card body -->
                <div class="card-body">
                  <div class="d-flex align-items-center justify-content-between mb-3 lh-1">
                    <div>
                      <span class="font-size-xs text-uppercase font-weight-semi-bold">Porteur de projet</span>
                    </div>
                    <div>
                      <a target="_blank" asp-controller="Candidats" asp-action="Index" asp-route-SearchStatut="0"><span class=" fe fe-user-check font-size-lg text-primary"></span></a>
                    </div>
                  </div>
                  <h2 class="font-weight-bold mb-1">
                    @Model.nombrePorteurDeProjets
                  </h2>
                  @*<span class="text-success font-weight-semi-bold"><i class="fe fe-trending-up mr-1"></i>+200</span>*@
                  <span class="ml-1 font-weight-medium">Nombre de porteur de projet</span>
                </div>
              </div>
            </div>

          </div>
    <div class="row">
        <div class="col-xl-6 col-lg-12 col-md-12 col-12">
            <!-- Card -->
            <div class="card mb-4">
                <!-- Card header -->
                <div class="card-header align-items-center card-header-height  d-flex justify-content-between align-items-center">
                    <div>
                        <h4 class="mb-0">Homme : @Model.nombreHommes - Femme : @Model.nombreFemmes</h4>
                    </div>

                </div>
                <!-- Card body -->
                <div class="card-body">
                    <div id="HF" class="apex-charts d-flex justify-content-center" style=""></div>
                </div>
            </div>
        </div>
         <div class="col-xl-6 col-lg-12 col-md-12 col-12">
            <!-- Card -->
            <div class="card mb-4">
                <!-- Card header -->
                <div class="card-header align-items-center card-header-height  d-flex justify-content-between align-items-center">
                    <div>
                        <h4 class="mb-0">Porteur de projet : @Model.nombrePorteurDeProjets - Chercheur d'emploit : @Model.nombreChercheurEmploit</h4>
                    </div>

                </div>
                <!-- Card body -->
                <div class="card-body">
                    <div id="PPCE" class="apex-charts d-flex justify-content-center" style=""></div>
                </div>
            </div>
        </div>
        <div class="col-xl-6 col-lg-12 col-md-12 col-12">
            <!-- Card -->
            <div class="card mb-4">
                <!-- Card header -->
                <div class="card-header align-items-center card-header-height  d-flex justify-content-between align-items-center">
                    <div>
                        <h4 class="mb-0">Orienté : @Model.nombreCandidatAcceuilliEtOriente - Non orienté : @Model.nombreCandidatNonOrienté - Refusé : @Model.nombreCandidatRefusé</h4>
                    </div>

                </div>
                <!-- Card body -->
                <div class="card-body">
                    <div id="ORN" class="apex-charts d-flex justify-content-center" style=""></div>
                </div>
            </div>
        </div>

    </div>
    
</div>







@section Scripts{

    <script>
        var options = {
            series: [@Html.DisplayFor(modelItem => modelItem.nombreHommes) , @Html.DisplayFor(modelItem => modelItem.nombreFemmes)],
            chart: {
                width: 430,
                type: 'pie',
            },
            labels: ['Homme ', 'Femme'],
            responsive: [{
                breakpoint: 516,
                options: {
                    chart: {
                        width: 380
                    },
                    legend: {
                        position: 'bottom'
                    }
                }
            }]
        };

        var chart = new ApexCharts(document.querySelector("#HF"), options);
        chart.render();
    </script>

    <script>
        var options = {
            series: [@Html.DisplayFor(modelItem => modelItem.nombrePorteurDeProjets) , @Html.DisplayFor(modelItem => modelItem.nombreChercheurEmploit)],
            chart: {
                width: 490,
                type: 'pie',
            },
            labels: ['Porteur de projet', 'Chercheur d\emploit'],
            responsive: [{
                breakpoint: 516,
                options: {
                    chart: {
                        width: 380
                    },
                    legend: {
                        position: 'bottom'
                    }
                }
            }]
        };

        var chart = new ApexCharts(document.querySelector("#PPCE"), options);
        chart.render();
    </script>

    <script>
        var options = {
            series: [@Html.DisplayFor(modelItem => modelItem.nombreCandidatAcceuilliEtOriente) , @Html.DisplayFor(modelItem => modelItem.nombreCandidatRefusé), @Html.DisplayFor(modelItem => modelItem.nombreCandidatNonOrienté)],
            chart: {
                width: 430,
                type: 'pie',
            },
            labels: ['Orienté ', 'Refusé', 'Non orienté'],
            responsive: [{
                breakpoint: 516,
                options: {
                    chart: {
                        width: 380
                    },
                    legend: {
                        position: 'bottom'
                    }
                }
            }]
        };

        var chart = new ApexCharts(document.querySelector("#ORN"), options);
        chart.render();
    </script>

  }