PlateformeDesJeunesV7/Controllers/AuthenticationController.cs
using Domain.Entities;
using Domain.Models;
using Domain.Models.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Service.IService;
using System.Web;

namespace PlateformeDesJeunesAinSebaa.Controllers
{
#nullable disable
    public class AuthenticationController : Controller
    {
        private readonly IAuthenticationService _authenticationService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailService _emailService;
        private readonly IRecaptchaService _verificationService;
        private CaptchaSettings _captchaSettings;

        public AuthenticationController(IAuthenticationService authenticationService, UserManager<ApplicationUser> userManager,
            IEmailService emailService, IRecaptchaService verificationService, IOptions<CaptchaSettings> captchaSettings)
        {
            _authenticationService = authenticationService;
            _userManager = userManager;
            _emailService = emailService;
            _verificationService = verificationService;
            _captchaSettings = captchaSettings.Value;
        }

        [HttpGet]
        public IActionResult Login(string Success)
        {
            ViewData["ClientKey"] = _captchaSettings.ClientKey;
            if (Success == "1") ViewData["ClientPublicSucess"] = "1";
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginModel user)
        {
            try
            {
                // validate input
                var requestIsValid = await _verificationService.IsCaptchaValid(user.CaptchaResponse);
                if (requestIsValid)
                {
                    var userAuth = await _authenticationService.Login(user);
                    if (!userAuth.Success)
                    {
                        ViewData["ClientKey"] = _captchaSettings.ClientKey;
                        TempData["LoginError"] = userAuth.Message;
                        return View();
                    }

                    var roles = userAuth.Message.Split(',');

                    if (User.IsInRole("GestionneurBlog"))
                    {
                        return RedirectToAction("Index", "GestionContenu");
                    }
                    if (roles.Contains("GestionnaireFamille") && !roles.Contains("Admin"))
                    {
                        return RedirectToAction("Index", "Famille");
                    }
                    return RedirectToAction("Index", "Candidats");
                }
                ViewData["ClientKey"] = _captchaSettings.ClientKey;
                TempData["LoginError"] = "Veuiller confirmer que vous n'êtes pas un robot.";
                return View();
            }
            catch (Exception ex)
            {
                ViewData["ClientKey"] = _captchaSettings.ClientKey;
                TempData["LoginError"] = ex.Message.ToString();
                return View();
            }

        }


        [HttpGet]
        public IActionResult EmailConfirmation()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Register()
        {
            ViewData["ClientKey"] = _captchaSettings.ClientKey;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterModel user)
        {
            try
            {
                var requestIsValid = await _verificationService.IsCaptchaValid(user.CaptchaResponse);
                if (requestIsValid)
                {
                    var userAuth = await _authenticationService.Register(user);
                    if (!userAuth.Success)
                    {
                        TempData["LoginError"] = userAuth.Message;
                        ViewData["ClientKey"] = _captchaSettings.ClientKey;
                        return View();
                    }
                    //var user2 = await _userManager.FindByIdAsync(userAuth.Message2);
                    //var code = await _userManager.GenerateEmailConfirmationTokenAsync(
                    //   user2);
                    //string codeHtmlVersion = HttpUtility.UrlEncode(code);

                    //var link = Url.Action(nameof(VerifyEmail), "Authentication", new { userId = userAuth.Message2, code = codeHtmlVersion }, Request.Scheme, Request.Host.ToString());
                    //await _emailService.SendEmailAsyncConfirmEmail(user.Email, "Confirmation email", link);
                    return RedirectToAction("EmailConfirmation", "Authentication");
                }
                ViewData["ClientKey"] = _captchaSettings.ClientKey;
                TempData["LoginError"] = "Veuiller confirmer que vous n'êtes pas un robot.";
                return View();
            }
            catch (Exception ex)
            {
                ViewData["Message"] = ex.Message;
                return View();
            }

        }

        [HttpGet]
        public async Task<IActionResult> VerifyEmail(string userId, string code)
        {
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null) return BadRequest();
            else
            {
                var result = await _userManager.ConfirmEmailAsync(user, HttpUtility.UrlDecode(code));
                if (result.Succeeded)
                {
                    return View();
                }
                else
                {
                    return BadRequest();
                }

            }
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await _authenticationService.Logout();
            return RedirectToAction("Login", "Authentication");
        }

        public IActionResult AccessDenied()
        {
            if (User.IsInRole("Finance"))
            {
                return RedirectToAction("Index", "Finances");
            }
            if (User.IsInRole("GestionneurBlog"))
            {
                return RedirectToAction("Index", "GestionContenu");
            }
            return View();
        }

    }
}

PlateformeDesJeunesV7/Controllers/DemandCandidateController.cs
using Domain.Enums;
using Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Service.IService;

namespace Web.Controllers
{
#nullable disable
    public class DemandCandidateController : Controller
    {
        private readonly ICandidatPublicService _candidatPublicService;
        private readonly IEmailService _emailService;

        public DemandCandidateController(ICandidatPublicService candidatPublicService, IEmailService emailService)
        {
            _candidatPublicService = candidatPublicService;
            _emailService = emailService;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(CreateClient model)
        {
            try
            {
                Response responseDocument = new();
                Response responseDiplome = new();
                Response response = await _candidatPublicService.AddCandidat(model.Candidat);
                if (model.DocumentModel != null)
                {
                    responseDocument = await _candidatPublicService.AddDocument(model.DocumentModel, response.ID);
                }
                if (model.DiplomeModel != null)
                {
                    responseDiplome = await _candidatPublicService.AddDiplome(model.DiplomeModel, response.ID);
                }
                /*if (!responseDocument.Success || !responseDiplome.Success)
                {
                    ViewData["MessageDiplome"] = responseDiplome.Message;
                    Console.WriteLine(responseDiplome.Message2);
                    ViewData["MessageDocument"] = responseDocument.Message;
                    Console.WriteLine(responseDocument.Message2);
                    ViewData["Message"] = response.Message;
                    Console.WriteLine(response.Message2);
                    return View(model);
                }*/
                //await _emailService.SendEmailAsync("badredine_moussaoui@hotmail.com", "Demande d\'inscription", "https://www.plateformedesjeunes-ainsebaa.com/GestionCandidatPublic/Details/" + response.ID, null);
                if (!response.Success)
                {
                    return View(model);
                }
                return RedirectToAction("Login", "Authentication", new { Success = "1", CandidatId = response.ID });
            }
            catch (Exception)
            {
                return View(model);
            }
        }
    }
}

PlateformeDesJeunesV7/Views/Authentication/AccessDenied.cshtml
@using Microsoft.AspNetCore.Identity
@using Domain.Entities


@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    Layout = null;
}

<style>
    body {
        background-color: black;
        color: white;
    }

    h1 {
        color: red;
    }

    h6 {
        color: red;
        text-decoration: underline;
    }
    .btn_return{
        margin-top: 10px;
        width : 100%;
        text-align: center;
        
    }
    .btn_return a{
        border: solid red 3px;
        background-color:red;
        color:white;
        border-radius:10px;
        text-decoration:none;
        padding:10px;
    }

</style>



<!DOCTYPE html>
<html>
<head>
    <title>Access Denied</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="UTF-8">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
    <div class="w3-display-middle" style="
    text-align: center;">
        <h1 class="w3-jumbo w3-animate-top w3-center"><code>Access Denied</code></h1>
        <hr class="w3-border-white w3-animate-left" style="margin:auto;width:50%">
        <h3 class="w3-center w3-animate-right">You dont have permission to view this page.</h3>
        <h3 class="w3-center w3-animate-zoom">🚫🚫🚫🚫</h3>
        <h6 class="w3-center w3-animate-zoom">error code:403 forbidden</h6>
        
        <br />
        
        <br />
        <div class="btn_return">
            <a class="w3-center w3-animate-zoom" asp-action="Logout" asp-controller="Authentication">Se connecter avec un autre compte</a>
        </div>
        
    </div>
</body>
</html>

PlateformeDesJeunesV7/Views/Authentication/EmailConfirmation.cshtml
@model Domain.Models.Authentication.LoginModel
@{
    Layout = "";

}


<!DOCTYPE html>
<html lang="en">


<!-- Mirrored from www.kodlama.org/pages/sign-in.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 30 Jun 2022 12:30:51 GMT -->
<!-- Added by HTTrack -->
<meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Favicon icon-->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/logo143.jpeg">


    <!-- Libs CSS -->
    <link href="~/Design/fonts/feather/feather.css" rel="stylesheet" />
    <link href="~/Design/libs/dragula/dist/dragula.min.css" rel="stylesheet" />
    <link href="~/Design/libs/mdi/font/css/materialdesignicons.min.css" rel="stylesheet" />
    <link href="~/Design/libs/prismjs/themes/prism.css" rel="stylesheet" />
    <link href="~/Design/libs/dropzone/dist/dropzone.css" rel="stylesheet" />
    <link href="~/Design/libs/magnific-popup/dist/magnific-popup.css" rel="stylesheet" />
    <link href="~/Design/libs/bootstrap-select/dist/css/bootstrap-select.min.css" rel="stylesheet">
    <link href="~/Design/libs/yaireo/tagify/dist/tagify.css" rel="stylesheet">
    <link href="~/Design/libs/tiny-slider/dist/tiny-slider.css" rel="stylesheet">
    <link href="~/Design/libs/tippy.js/dist/tippy.css" rel="stylesheet">
    <link href="~/Design/libs/cd" rel="stylesheet">

    <link href="~/Design/libs/cdnjscloudflarecom/ajax/libs/font-awesome\5.11.2/css/all.css" rel="stylesheet">


    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Design/css/theme.min.css">
    <title>Authentification plateforme des jeunes</title>
</head>

<body>
    <!-- Page content -->
    <div class="container d-flex flex-column">
        <div class="row align-items-center justify-content-center no-gutters min-vh-100">
            <div class="col-lg-5 col-md-8 py-8 py-xl-0">
                <!-- Card -->
                <div class="card shadow ">
                    <!-- Card body -->
                    <div class="card-body p-6">
                        <div class="mb-4">
                            <div style="display:flex;justify-content:center;">
                                <div><a asp-area="Identity" asp-page="/Account/Login"><img src="~/assets/images/logo143.jpeg" class="mb-1" alt="" style="width:150px;height:150px;"></a></div>
                                @*<div><a href="https://www.kodlama.org/index.html"><img src="~/assets/images/Image1-removebg-preview.png" class="mb-4" alt="" style="width:140px;height:90px;padding-top: 30px;"></a></div>*@
                            </div>

@*                             <h1 class="mb-1 font-weight-bold">Veuiller confirmer votre adresse Email, un email vous a été envoyé</h1>
 *@
                            <h1 class="mb-1 font-weight-bold">Félicitation votre demande d'inscription a été transmis pour validation...</h1>

                        </div>
                       
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <!-- Libs JS -->
    <script src="~/Design/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/Design/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Design/libs/odometer/odometer.min.js"></script>
    <script src="~/Design/libs/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/Design/libs/magnific-popup/dist/jquery.magnific-popup.min.js"></script>
    <script src="~/Design/libs/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/Design/libs/flatpickr/dist/flatpickr.min.js"></script>
    <script src="~/Design/libs/inputmask/dist/jquery.inputmask.min.js"></script>
    <script src="~/Design/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="~/Design/libs/quill/dist/quill.min.js"></script>
    <script src="~/Design/libs/file-upload-with-preview/dist/file-upload-with-preview.min.js"></script>
    <script src="~/Design/libs/dragula/dist/dragula.min.js"></script>
    <script src="~/Design/libs/bs-stepper/dist/js/bs-stepper.min.js"></script>
    <script src="~/Design/libs/dropzone/dist/min/dropzone.min.js"></script>
    <script src="~/Design/libs/jQuery.print/jQuery.print.js"></script>
    <script src="~/Design/libs/prismjs/prism.js"></script>
    <script src="~/Design/libs/prismjs/components/prism-scss.min.js"></script>
    <script src=""></script>

    <script src="~/Design/libs/yaireo/tagify/dist/tagify.min.js"></script>
    <script src="~/Design/libs/tiny-slider/dist/min/tiny-slider.js"></script>
    <script src="~/Design/libs/popperjs/core/dist/umd/popper.min.js"></script>
    <script src="~/Design/libs/tippy.js/dist/tippy-bundle.umd.min.js"></script>
    <script src="~/Design/libs/typed.js/lib/typed.min.js"></script>

    <!-- clipboard -->
    <script src="~/Design/libs/cdnjscloudflarecom/ajax/libs/clipboard.js/1.5.12/clipboard.min.js"></script>


    <!-- Theme JS -->
    <script src="~/Design/js/theme.min.js"></script>

</body>


<!-- Mirrored from www.kodlama.org/pages/sign-in.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 30 Jun 2022 12:30:51 GMT -->
</html>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(document).ready(function () {
            

        });

    </script>

}

PlateformeDesJeunesV7/Views/Authentication/Login.cshtml
@model Domain.Models.Authentication.LoginModel
@{
    Layout = "";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- Amélioration de la compatibilité avec IE -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Optimisation SEO -->
    <title>Plateforme des Jeunes INDH Ain Sebaa - Amélioration du Revenu et Inclusion Économique des Jeunes</title>
    <meta name="description" content="Plateforme des Jeunes INDH Ain Sebaa s'engage dans l'amélioration du revenu et l'inclusion économique des jeunes. Rejoignez-nous pour faire la différence.">
    <meta name="robots" content="index, follow, max-image-preview:large">
    <link rel="canonical" href="https://plateformedesjeunes-ainsebaa.ma">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:title" content="Plateforme des Jeunes INDH Ain Sebaa - Amélioration du Revenu et Inclusion Économique des Jeunes">
    <meta property="og:description" content="Plateforme des Jeunes INDH Ain Sebaa s'engage dans l'amélioration du revenu et l'inclusion économique des jeunes. Rejoignez-nous pour faire la différence.">
    <meta property="og:url" content="https://www.facebook.com/plateformedesjeunes.as">
    <meta property="og:site_name" content="Plateforme des Jeunes INDH Ain Sebaa">
    <meta property="og:locale" content="fr_FR">
    <meta property="og:image" content="https://scontent.fcmn2-2.fna.fbcdn.net/v/t39.30808-6/277250841_298291872425465_2706695951558468858_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=efb6e6&_nc_eui2=AeE1KGfknEMBfDvIhRVglaRBZlQGzk7xNK5mVAbOTvE0rqUZU2kk6oWDv2XGAg8i1jzRaYWsmQPIjeOeoQdDixoc&_nc_ohc=WVgXaozbJTgAX9N_XBG&_nc_ht=scontent.fcmn2-2.fna&oh=00_AfAxstddXsy3iets1Km3UanRB38ZDPbcgFvcHSZRv9TxdA&oe=65B6B94D">

    <!-- Lien vers Instagram -->
    <meta property="og:instagram" content="https://www.instagram.com/plateformedesjeunes.as/?igshid=YmMyMTA2M2Y%3D">

    <!-- Lien vers LinkedIn -->
    <meta name="linkedin:site" content="Plateforme des Jeunes INDH Ain Sebaa">
    <meta name="linkedin:description" content="Plateforme des Jeunes INDH Ain Sebaa s'engage dans l'amélioration du revenu et l'inclusion économique des jeunes. Rejoignez-nous pour faire la différence.">
    <meta name="linkedin:image" content="https://scontent.fcmn2-2.fna.fbcdn.net/v/t39.30808-6/277250841_298291872425465_2706695951558468858_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=efb6e6&_nc_eui2=AeE1KGfknEMBfDvIhRVglaRBZlQGzk7xNK5mVAbOTvE0rqUZU2kk6oWDv2XGAg8i1jzRaYWsmQPIjeOeoQdDixoc&_nc_ohc=WVgXaozbJTgAX9N_XBG&_nc_ht=scontent.fcmn2-2.fna&oh=00_AfAxstddXsy3iets1Km3UanRB38ZDPbcgFvcHSZRv9TxdA&oe=65B6B94D">
    <meta name="linkedin:owner" content="plateforme des jeunes INDH - AIN SBAA">

    <!-- Ajout d'une image pour le partage social (taille recommandée : 1200x630 pixels) -->
    <meta property="og:image" content="~/assets/images/logo143.jpeg">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">

    <!-- Twitter Card -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@@Association l'Heure Joyeuse">
    <meta name="twitter:title" content="Plateforme des Jeunes INDH Ain Sebaa">
    <meta name="twitter:description" content="Plateforme des Jeunes INDH Ain Sebaa s'engage dans l'amélioration du revenu et l'inclusion économique des jeunes. Rejoignez-nous pour faire la différence.">
    <meta name="twitter:image" content="https://scontent.fcmn2-2.fna.fbcdn.net/v/t39.30808-6/277250841_298291872425465_2706695951558468858_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=efb6e6&_nc_eui2=AeE1KGfknEMBfDvIhRVglaRBZlQGzk7xNK5mVAbOTvE0rqUZU2kk6oWDv2XGAg8i1jzRaYWsmQPIjeOeoQdDixoc&_nc_ohc=WVgXaozbJTgAX9N_XBG&_nc_ht=scontent.fcmn2-2.fna&oh=00_AfAxstddXsy3iets1Km3UanRB38ZDPbcgFvcHSZRv9TxdA&oe=65B6B94D">

    <!-- Ajout de la balise meta pour la compatibilité mobile -->
    <meta name="format-detection" content="telephone=no">

    <!-- Favicon icon-->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/logo143.jpeg">
    <!-- Favicon icon-->
    <script type="text/javascript">
        var onloadCallback = function () {
            grecaptcha.render('recaptcha_div', {
                'sitekey': '@ViewData["ClientKey"]'
            });
        };
    </script>
    @*<script src="https://www.google.com/recaptcha/api.js" async defer></script>*@
    <!-- Libs CSS -->
    <link href="~/Design/libs/bootstrap-select/dist/css/bootstrap-select.min.css" rel="stylesheet">
    <link href="~/css/AnimationLogin.css" rel="stylesheet">
    <link href="~/Design/libs/cdnjscloudflarecom/ajax/libs/font-awesome\5.11.2/css/all.css" rel="stylesheet">
    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Design/css/theme.min.css">
</head>

<body>
    <!-- Page content -->
    <div class="container d-flex flex-column">
        <div class="row align-items-center justify-content-center no-gutters min-vh-100">
            <div class="col-lg-5 col-md-8 py-8 py-xl-0">
                <!-- Card -->
                <div class="card shadow ">
                    <!-- Card body -->
                    <div class="card-body p-6">
                        <div class="mb-4">
                            <div style="display:flex;justify-content:center;">
                                <div><a asp-area="Identity" asp-page="/Account/Login"><img src="~/assets/images/logo143.jpeg" class="mb-1" alt="Plateforme des jeunes Ain Sebaa - Amélioration du Revenu et Inclusion Économique des Jeunes" style="width:150px;height:150px;"></a></div>
                            </div>
                            
                            <h1 class="mb-1 font-weight-bold">Plateforme des jeunes INDH - AIN SEBAA</h1>
                            <h3 class="mb-1 font-weight-bold">Authentification</h3>
                            <span>Vous n'avez pas de compte? <a asp-action="Register" asp-controller="Authentication" class="ml-1" style="color:#00AFF5!important;">Inscription</a></span>
                        </div>
                        <!-- Form -->
                        <form method="post">
                            <!-- Username -->
                            <div class="form-group">
                                <label for="email" class="form-label">Email</label>
                                <input asp-for="UserName" type="text" id="UserName" class="form-control" placeholder="Votre nom d'utilisateur ici" required>
                                <div class="invalid-feedback">
                                    Veuillez entrer votre nom d'utilisateur
                                </div>
                                <span asp-validation-for="UserName" class="text-danger"></span>
                            </div>
                            <!-- Password -->
                            <div class="form-group">
                                <label for="password" class="form-label">Mot de passe</label>
                                <input asp-for="Password" type="password" id="password" class="form-control" placeholder="**************"
                                       required>
                                <div class="invalid-feedback">
                                    Veuillez entrer le mot de passe
                                </div>
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div>
                            <!-- Checkbox -->
                           @* <div class="d-lg-flex justify-content-between align-items-center mb-4">
                                <div class="custom-control custom-checkbox">
                                    <input type="checkbox" class="custom-control-input" id="rememberme">
                                    <label class="custom-control-label " for="rememberme">Se souvenir de moi</label>
                                </div>
                                <div>
                                    <a href="forget-password.html">Forgot your password?</a>
                                </div>
                            </div>*@
                            <div id="recaptcha_div"></div>

                            <br />
                            <div id="mesBoutons">
                                @*<div class="g-recaptcha" data-sitekey="6LeYP9ciAAAAALwP8XXPMdJWwCoKOPWd8OeC1dx5"></div>*@

                                <h5 style="color:darkgreen;text-decoration: underline;">@ViewData["ClientPublicSucess"]</h5>
                                <h5 style="color:#ff0000b3;text-decoration: underline;">@TempData["LoginError"]</h5>
                                <!-- Button -->
                                <button type="submit" class="btn btn-block" style="background-color:#00AFF5;color:white;">S'authentifier</button>
                                <a class="btn btn-block attention" style="background-color:#0074A3;color:white;" asp-controller="DemandCandidate" asp-action="Add">Poster ma candidature</a>

                            </div>
                            <hr class="my-4">
                            <div class="font-size-md mt-4 text-center">
                                <a href="https://www.facebook.com/منصة-الشباب-عين-السبع-107323618188959/" class="fab fa-facebook text-muted mr-3"></a>
                                <a href="https://instagram.com/plateformedesjeunes.as?igshid=YmMyMTA2M2Y=" class="fab fa-instagram text-muted mr-3"></a>
                                <a href="https://www.linkedin.com/company/plateforme-des-jeunes-ain-sbaa/" class="fab fa-linkedin text-muted "></a>
                            </div>
      
                        </form>
                    </div>
                </div>           
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
            async defer>
    </script>
    <!-- Libs JS -->
    <script src="~/Design/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/Design/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Design/libs/odometer/odometer.min.js"></script>
    <script src="~/Design/libs/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/Design/libs/magnific-popup/dist/jquery.magnific-popup.min.js"></script>
    <script src="~/Design/libs/bootstrap-select/dist/js/bootstrap-select.min.js"></script>
    <script src="~/Design/libs/flatpickr/dist/flatpickr.min.js"></script>
    <script src="~/Design/libs/inputmask/dist/jquery.inputmask.min.js"></script>
    <script src="~/Design/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="~/Design/libs/quill/dist/quill.min.js"></script>
    <script src="~/Design/libs/file-upload-with-preview/dist/file-upload-with-preview.min.js"></script>
    <script src="~/Design/libs/dragula/dist/dragula.min.js"></script>
    <script src="~/Design/libs/bs-stepper/dist/js/bs-stepper.min.js"></script>
    <script src="~/Design/libs/dropzone/dist/min/dropzone.min.js"></script>
    <script src="~/Design/libs/jQuery.print/jQuery.print.js"></script>
    <script src="~/Design/libs/prismjs/prism.js"></script>
    <script src="~/Design/libs/prismjs/components/prism-scss.min.js"></script>

    <script src="~/Design/libs/yaireo/tagify/dist/tagify.min.js"></script>
    <script src="~/Design/libs/tiny-slider/dist/min/tiny-slider.js"></script>
    <script src="~/Design/libs/popperjs/core/dist/umd/popper.min.js"></script>
    <script src="~/Design/libs/tippy.js/dist/tippy-bundle.umd.min.js"></script>
    <script src="~/Design/libs/typed.js/lib/typed.min.js"></script>

    <!-- clipboard -->
    <script src="~/Design/libs/cdnjscloudflarecom/ajax/libs/clipboard.js/1.5.12/clipboard.min.js"></script>


    <!-- Theme JS -->
    <script src="~/Design/js/theme.min.js"></script>

</body>


<!-- Mirrored from www.kodlama.org/pages/sign-in.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 30 Jun 2022 12:30:51 GMT -->
</html>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        $(document).ready(function() {
            if (@ViewData["ClientPublicSucess"]== "1") {
                alertify.success('Candidat ajoutée avec succée.');
            }
            
        });

    </script>
    <script src="~/js/cercles.js"></script>
}