PlateformeDesJeunesV7/Controllers/FamilleController.cs
using KhalfiElection.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PlateformeDesJeunesV7.Controllers;
using Repository.Data;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;
using Domain.Models.Election;
using Domain.Entities.V2;
using Repository.Data.Migrations;
using Microsoft.AspNetCore.Authorization;
using OfficeOpenXml.Style;
using OfficeOpenXml;
using System.Drawing;

namespace Web.Controllers
{
    [Authorize(Roles = "Admin, GestionnaireFamille")]
    public class FamilleController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public FamilleController(ILogger<HomeController> logger, ApplicationDbContext dbContext)
        {
            _logger = logger;
            _context = dbContext;
        }

#nullable disable
        public async Task<IActionResult> Index(StatistiqueFamille model)
        {
            try
            {
                var datenow = DateTime.Now.Date;
                var nextMonth = datenow.AddMonths(1);
                var startDay = datenow.Day;
                var endDay = datenow.Day;

                var anniversaireProche = await _context.PersonnePivot
                    .Where(c => c.DateNaissance != null &&
                                ((c.DateNaissance.Value.Month == nextMonth.Month && c.DateNaissance.Value.Day >= startDay) ||
                                 (c.DateNaissance.Value.Month == nextMonth.AddMonths(1).Month && c.DateNaissance.Value.Day <= endDay)))
                    .Select(c => new PersonnePivot
                    {
                        Nom = c.Nom + " " + c.Prenom,
                        DateNaissance = c.DateNaissance,
                        GSM = c.GSM,
                        Adresse = c.Adresse,
                        Secteur = c.Secteur,
                        DateCreation = c.DateCreation
                    })
                    .ToListAsync();

                var anniversaireProcheResponsables = await _context.PersonneResponsable
                    .Where(c => c.DateNaissance != null &&
                                ((c.DateNaissance.Value.Month == nextMonth.Month && c.DateNaissance.Value.Day >= startDay) ||
                                 (c.DateNaissance.Value.Month == nextMonth.AddMonths(1).Month && c.DateNaissance.Value.Day <= endDay)))
                    .Select(c => new PersonnePivot
                    {
                        Nom = c.Nom + " " + c.Prenom,
                        DateNaissance = c.DateNaissance,
                        GSM = c.GSM,
                        Adresse = c.Adresse,
                        Secteur = c.Secteur,
                        DateCreation = c.DateCreation
                    })
                    .ToListAsync();

                var anniversaireProcheMembres = await _context.PersonneMembre
                    .Where(c => c.DateNaissance != null &&
                                ((c.DateNaissance.Value.Month == nextMonth.Month && c.DateNaissance.Value.Day >= startDay) ||
                                 (c.DateNaissance.Value.Month == nextMonth.AddMonths(1).Month && c.DateNaissance.Value.Day <= endDay)))
                    .Select(c => new PersonnePivot
                    {
                        Nom = c.Nom + " " + c.Prenom,
                        DateNaissance = c.DateNaissance,
                        GSM = c.GSM,
                        Adresse = c.Adresse,
                        Secteur = c.Secteur,
                        DateCreation = c.DateCreation
                    })
                    .ToListAsync();

                var allAnniversairesProche = anniversaireProche.Concat(anniversaireProcheResponsables)
                                                              .Concat(anniversaireProcheMembres)
                                                              .ToList();

                ViewBag.AnniversaireProche = allAnniversairesProche;


            }
            catch (Exception ex)
            {
                
            }

            var secteurs = await _context.Secteurs.ToListAsync();
            var pivots = await _context.PersonnePivot.ToListAsync();

            ViewBag.Pivot = pivots;
            ViewBag.Secteur = secteurs;

            if (model.SecteurId == null && model.PivotId == null && model.ResponsableId == null && model.MembreId == null && string.IsNullOrEmpty(model.SearchNom) && string.IsNullOrEmpty(model.SearchCIN) && (model?.TotalGeneral == null || model?.TotalGeneral == 0))
            {
                return View(model);
            }

            var membres = _context.PersonnePivot
                .Include(c => c.Secteur)
                .Include(c => c.Responsables)
                .ThenInclude(c => c.Membres)
                .ThenInclude(c => c.RelationParente)
                .AsQueryable();

            //Récupération du pivot et de ses responsables et membres
            if (model.PivotId != null && model.PivotId != 0)
            {
                membres = membres.Where(c => c.PersonnePivotId == model.PivotId || c.Responsables.Any(a => a.PivotId == model.PivotId) || c.Responsables.Any(b => b.Pivot.PersonnePivotId == model.PivotId));
            }
            if(model.ResponsableId != null && model.ResponsableId != 0)
            {
                membres = membres.Where(c => c.Responsables.Any(r => r.PersonneResponsableId == model.ResponsableId));
            }
            if (model.MembreId != null && model.MembreId != 0)
            {
                membres = membres.Where(c => c.Responsables.Any(m => m.Membres.Any(m => m.PersonneMembreId == model.MembreId)));
            }
            if (model.SecteurId != null && model.SecteurId != 0)
            {
                membres = membres.Where(c => c.SecteurId == model.SecteurId || c.Responsables.Any(a => a.SecteurId == model.SecteurId) || c.Responsables.Any(b => b.Pivot.SecteurId == model.SecteurId));
            }
            if (!string.IsNullOrEmpty(model.SearchNom))
            {
                membres = membres.Where(c => c.Nom.Contains(model.SearchNom) || c.Prenom.Contains(model.SearchNom) || c.Responsables.Any(a => a.Nom == model.SearchNom || a.Prenom == model.SearchNom) || c.Responsables.Any(b => b.Nom == model.SearchNom || b.Prenom == model.SearchNom));
            }
            if (!string.IsNullOrEmpty(model.SearchCIN))
            {
                membres = membres.Where(c => c.CIN.Contains(model.SearchCIN) || c.Responsables.Any(a => a.CIN == model.SearchCIN) || c.Responsables.Any(b => b.Pivot.CIN == model.SearchCIN));
            }

            var result = await membres.ToListAsync();
            model.PersonnePivot = result;

            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        // GET: Personnes/Create
        public async Task<IActionResult> CreatePivot()
        {
            var pivots = await _context.PersonnePivot.ToListAsync();

            ViewBag.Pivot = pivots; ViewData["RelationParenteId"] = new SelectList(await _context.TypesRelationParente.ToListAsync(), "Id", "Nom");
            ViewData["SecteurId"] = new SelectList(await _context.Secteurs.ToListAsync(), "Id", "Nom");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePivot(PersonnePivot personne)
        {
            try
            {
                var CINExist = await _context.PersonnePivot.AnyAsync(c => c.CIN == personne.CIN) || await _context.PersonneResponsable.AnyAsync(c => c.CIN == personne.CIN) || await _context.PersonneMembre.AnyAsync(c => c.CIN == personne.CIN);
                if(CINExist == true)
                {
                    ViewData["SecteurId"] = new SelectList(await _context.Secteurs.ToListAsync(), "Id", "Nom");
                    ModelState.AddModelError("CIN", "Ce CIN existe déjà");
                    return View(personne);
                }
                await _context.PersonnePivot.AddAsync(personne);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }

        public async Task<IActionResult> CreateResponsable()
        {
            var pivots = await _context.PersonnePivot.ToListAsync();

            ViewBag.Pivot = pivots; 
            ViewData["RelationParenteId"] = new SelectList(await _context.TypesRelationParente.ToListAsync(), "Id", "Nom");
            ViewData["SecteurId"] = new SelectList(await _context.Secteurs.ToListAsync(), "Id", "Nom");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateResponsable(PersonneResponsable personne)
        {
            try
            {
                var CINExist = await _context.PersonnePivot.AnyAsync(c => c.CIN == personne.CIN) || await _context.PersonneResponsable.AnyAsync(c => c.CIN == personne.CIN) || await _context.PersonneMembre.AnyAsync(c => c.CIN == personne.CIN);
                if (CINExist == true)
                {
                    var pivots = await _context.PersonnePivot.ToListAsync();
                    ViewBag.Pivot = pivots;
                    ViewData["RelationParenteId"] = new SelectList(await _context.TypesRelationParente.ToListAsync(), "Id", "Nom");
                    ViewData["SecteurId"] = new SelectList(await _context.Secteurs.ToListAsync(), "Id", "Nom");

                    ModelState.AddModelError("CIN", "Ce CIN existe déjà");
                    return View(personne);
                }
                if (personne.PivotId == null || personne.PivotId == 0)
                {
                    ModelState.AddModelError("PivotId", "Veuiller selectionner un pivot"); 
                    return View(personne);
                }

PlateformeDesJeunesV7/Views/Famille/Create.cshtml
@model KhalfiElection.Models.Models.FamilleModel

@{
    Layout = "_LayoutDashboard";
    ViewData["Title"] = "Home Page";
    var pivots = ViewBag.Pivot as List<KhalfiElection.Models.Entities.Personne>;
    pivots = pivots?.Select(c => new KhalfiElection.Models.Entities.Personne
            {
                PersonneId = c.PersonneId,
                Nom = c.Nom + " " + c.Prenom
            }).ToList() ?? new List<KhalfiElection.Models.Entities.Personne>();
}

<div class="card mb-4">
    <div style="display:flex;justify-content:space-between;">
        <div class="card-header">
            <h3 class="mb-0">Pivot | Famille</h3>
            <span>
                Création
            </span>
        </div>
        <div class="card-header">
            <a type="button" class="btn btn-primary" asp-controller="Famille" asp-action="Index">Retour</a>
        </div>
    </div>

<div class="card-body">
    <!-- Form -->
    <form asp-action="Create" method="post" class="form-row mt-3">
                <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="Personne.Nom" class="control-label"></label>
                    <input asp-for="Personne.Nom" class="form-control" />
                    <span asp-validation-for="Personne.Nom" class="text-danger"></span>
                </div>
                <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="Personne.Prenom" class="control-label"></label>
                    <input asp-for="Personne.Prenom" class="form-control" />
                    <span asp-validation-for="Personne.Prenom" class="text-danger"></span>
                </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="Personne.CIN" class="control-label"></label>
                    <input asp-for="Personne.CIN" class="form-control" />
                    <span asp-validation-for="Personne.CIN" class="text-danger"></span>
                </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="Personne.DateNaissance" class="control-label">Date de naissance</label>
                    <input asp-for="Personne.DateNaissance" class="form-control" type="date"/>
                    <span asp-validation-for="Personne.DateNaissance" class="text-danger"></span>
                </div>
        <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="Personne.Adresse" class="control-label"></label>
                    <input asp-for="Personne.Adresse" class="form-control" />
                    <span asp-validation-for="Personne.Adresse" class="text-danger"></span>
                </div>
        <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="Personne.GSM" class="control-label"></label>
                    <input asp-for="Personne.GSM" class="form-control" />
                    <span asp-validation-for="Personne.GSM" class="text-danger"></span>
                </div>
    <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="Personne.SecteurId" class="control-label">Secteur</label>
                <select asp-for="Personne.SecteurId" class="selectpicker" data-width="100%" data-live-search="true" asp-items="ViewBag.SecteurId">
                    <option value="" selected>--Secteur--</option>
                </select>
                    <span asp-validation-for="Personne.SecteurId" class="text-danger"></span>
                </div>
<div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="Personne.RelationParenteId" class="control-label"> Relation familial</label>
                <select asp-for="Personne.RelationParenteId" class="selectpicker" data-width="100%" data-live-search="true" asp-items="ViewBag.RelationParenteId">
                    <option value="" selected>--Relation parenté--</option>
                </select>
                    <span asp-validation-for="Personne.RelationParenteId" class="text-danger"></span>
                </div>
<div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="Personne.PivotId" class="control-label">Pivot</label>
                <select asp-for="Personne.PivotId" class="selectpicker" data-width="100%" data-live-search="true" asp-items="@(new SelectList(pivots, "PersonneId", "Nom"))">
                    <option value="" selected>--Pivot--</option>
                </select>
                <span asp-validation-for="Personne.PivotId" class="text-danger"></span>
                </div>
            <div class="col-lg-12 col-md-12 col-12 mb-2" style="text-align:right!important;">
                <button type="submit" class="btn btn-outline-info me-2">Créer</button>
            </div>
        
    </form>
    </div>
@section Scripts {

    <script>

    </script>
}

PlateformeDesJeunesV7/Views/Famille/CreateMember.cshtml
@model Domain.Entities.V2.PersonneMembre
@using Newtonsoft.Json

@{
    Layout = "_LayoutDashboard2";
    ViewData["Title"] = "Création d'un membre";

    var pivots = ViewBag.Pivot as List<Domain.Entities.V2.PersonnePivot>;
    pivots = pivots?.Select(c => new Domain.Entities.V2.PersonnePivot
            {
                PersonnePivotId = c.PersonnePivotId,
                Nom = c.Nom + " " + c.Prenom
            }).ToList() ?? new List<Domain.Entities.V2.PersonnePivot>();
}

<div class="card mb-4">
    <div style="display:flex;justify-content:space-between;">
        <div class="card-header">
            <h3 class="mb-0">Membres </h3>
            <span>
                Création
            </span>
        </div>
        <div class="card-header">
            <a type="button" class="btn btn-primary" asp-controller="Famille" asp-action="Index">Retour</a>
        </div>
    </div>
</div>
    <div class="card-body">
        <!-- Form -->
        <form asp-action="CreateMember" method="post" class="form-row mt-3">
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="CIN" class="control-label"></label>
                <input asp-for="CIN" class="form-control" />
                <span asp-validation-for="CIN" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="DateNaissance" class="control-label">Date de naissance</label>
                <input asp-for="DateNaissance" class="form-control" type="date" />
                <span asp-validation-for="DateNaissance" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="GSM" class="control-label"></label>
                <input asp-for="GSM" class="form-control" />
                <span asp-validation-for="GSM" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="SecteurId" class="control-label">Secteur</label>
                <select asp-for="SecteurId" class="selectpicker" data-width="100%" data-live-search="true" asp-items="ViewBag.SecteurId">
                    <option value="" selected>--Secteur--</option>
                </select>
                <span asp-validation-for="SecteurId" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="RelationParenteId" class="control-label"> Relation familial</label>
                <select asp-for="RelationParenteId" class="selectpicker" data-width="100%" data-live-search="true" asp-items="ViewBag.RelationParenteId">
                    <option value="" selected>--Relation parenté--</option>
                </select>
                <span asp-validation-for="RelationParenteId" class="text-danger"></span>
            </div>
            <!--PIVOT-->
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label class="control-label">Pivot</label>
                <select id="pivot" asp-for="PivotId" class="selectpicker" data-width="100%" data-live-search="true" asp-items="@(new SelectList(pivots, "PersonnePivotId", "Nom"))">
                    <option value="" selected>--Pivot--</option>
                </select>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="ResponsableId" class="control-label">Responsable famille</label>
            <select required id="responsable" asp-for="ResponsableId" class="selectpicker" data-width="100%" data-live-search="true">
                    <option value="" selected>--Responsable famille--</option>
                </select>
                <span asp-validation-for="ResponsableId" class="text-danger"></span>
            </div>
            <div class="col-lg-12 col-md-12 col-12 mb-2" style="text-align:right!important;">
                <button type="submit" class="btn btn-outline-info me-2">Créer</button>
            </div>

        </form>
    </div>
    @section Scripts {

    <script>
        $(document).ready(function () {
            var responsablesJson = '@Html.Raw(ViewBag.Responsable)';

            var responsables = JSON.parse(responsablesJson);

            $('#pivot').change(function () {
                var pivotId = $(this).val();

                var responsablesFiltres = responsables.filter(responsable => responsable.PivotId == pivotId);

                // Remplir la liste déroulante des responsables avec les responsables filtrés
                var responsableList = $('#responsable');

                responsableList.empty(); // Efface les options actuelles de la liste déroulante des responsables

                responsableList.append($('<option>').text('--Responsable famille--').val('')); // Ajoute une option par défaut

                responsablesFiltres.forEach(function (responsable) {
                    responsableList.append($('<option>').text(responsable.Nom).val(responsable.PersonneResponsableId)); // Ajoute les options des responsables filtrés
                });

                $('.selectpicker').selectpicker('refresh')
            });
        });
    </script>
    }

PlateformeDesJeunesV7/Views/Famille/CreatePivot.cshtml
@model Domain.Entities.V2.PersonnePivot

@{
    Layout = "_LayoutDashboard2";
    ViewData["Title"] = "Création d'un pivot";
}

<div class="card mb-4">
    <div style="display:flex;justify-content:space-between;">
        <div class="card-header">
            <h3 class="mb-0">Pivot </h3>
            <span>
                Création
            </span>
        </div>
        <div class="card-header">
            <a type="button" class="btn btn-primary" asp-controller="Famille" asp-action="Index">Retour</a>
        </div>
    </div>

<div class="card-body">
    <!-- Form -->
    <form asp-action="CreatePivot" method="post" class="form-row mt-3">
                <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="Nom" class="control-label"></label>
                    <input asp-for="Nom" class="form-control" />
                    <span asp-validation-for="Nom" class="text-danger"></span>
                </div>
                <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="Prenom" class="control-label"></label>
                    <input asp-for="Prenom" class="form-control" />
                    <span asp-validation-for="Prenom" class="text-danger"></span>
                </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="CIN" class="control-label"></label>
                    <input asp-for="CIN" class="form-control" />

                    <span asp-validation-for="CIN" class="text-danger"></span>
                </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="DateNaissance" class="control-label">Date de naissance</label>
                    <input asp-for="DateNaissance" class="form-control" type="date"/>
                    <span asp-validation-for="DateNaissance" class="text-danger"></span>
                </div>
        <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="Adresse" class="control-label"></label>
                    <input asp-for="Adresse" class="form-control" />
                    <span asp-validation-for="Adresse" class="text-danger"></span>
                </div>
        <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="GSM" class="control-label"></label>
                    <input asp-for="GSM" class="form-control" />
                    <span asp-validation-for="GSM" class="text-danger"></span>
                </div>
    <div class="col-lg-6 mb-2 col-md-6 col-12">
                    <label asp-for="SecteurId" class="control-label">Secteur</label>
                <select asp-for="SecteurId" class="selectpicker" data-width="100%" data-live-search="true" asp-items="ViewBag.SecteurId">
                    <option value="" selected>--Secteur--</option>
                </select>
                    <span asp-validation-for="SecteurId" class="text-danger"></span>
                </div>

            <div class="col-lg-12 col-md-12 col-12 mb-2" style="text-align:right!important;">
                <button type="submit" class="btn btn-outline-info me-2">Créer</button>
            </div>
        
    </form>
    </div>
@section Scripts {

    <script>

    </script>
}

PlateformeDesJeunesV7/Views/Famille/CreateResponsable.cshtml
@model Domain.Entities.V2.PersonneResponsable

@{
    Layout = "_LayoutDashboard2";
    ViewData["Title"] = "Création d'un pivot";
    var pivots = ViewBag.Pivot as List<Domain.Entities.V2.PersonnePivot>;
    pivots = pivots?.Select(c => new Domain.Entities.V2.PersonnePivot
            {
                PersonnePivotId = c.PersonnePivotId,
                Nom = c.Nom + " " + c.Prenom
            }).ToList() ?? new List<Domain.Entities.V2.PersonnePivot>();
}

<div class="card mb-4">
    <div style="display:flex;justify-content:space-between;">
        <div class="card-header">
            <h3 class="mb-0">Responsable </h3>
            <span>
                Création
            </span>
        </div>
        <div class="card-header">
            <a type="button" class="btn btn-primary" asp-controller="Famille" asp-action="Index">Retour</a>
        </div>
    </div>

    <div class="card-body">
        <!-- Form -->
        <form asp-action="CreateResponsable" method="post" class="form-row mt-3">
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="CIN" class="control-label"></label>
                <input asp-for="CIN" class="form-control" />
                <span asp-validation-for="CIN" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="DateNaissance" class="control-label">Date de naissance</label>
                <input asp-for="DateNaissance" class="form-control" type="date" />
                <span asp-validation-for="DateNaissance" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="GSM" class="control-label"></label>
                <input asp-for="GSM" class="form-control" />
                <span asp-validation-for="GSM" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="SecteurId" class="control-label">Secteur</label>
                <select asp-for="SecteurId" class="selectpicker" data-width="100%" data-live-search="true" asp-items="ViewBag.SecteurId">
                    <option value="" selected>--Secteur--</option>
                </select>
                <span asp-validation-for="SecteurId" class="text-danger"></span>
            </div>
            
            <div class="col-lg-6 mb-2 col-md-6 col-12">
                <label asp-for="PivotId" class="control-label">Pivot</label>
                <select required asp-for="PivotId" class="selectpicker" data-width="100%" data-live-search="true" asp-items="@(new SelectList(pivots, "PersonnePivotId", "Nom"))">
                    <option value="" selected>--Pivot--</option>
                </select>
                <span asp-validation-for="PivotId" class="text-danger"></span>
            </div>
            <div class="col-lg-12 col-md-12 col-12 mb-2" style="text-align:right!important;">
                <button type="submit" class="btn btn-outline-info me-2">Créer</button>
            </div>

        </form>
    </div>
    @section Scripts {

        <script>

        </script>
    }

PlateformeDesJeunesV7/Views/Famille/EditPivot.cshtml
@model Domain.Entities.V2.PersonnePivot

@{
    Layout = "_LayoutDashboard2";
    ViewData["Title"] = "Édition d'un pivot";
}

<div class="card mb-4">
    <div style="display:flex;justify-content:space-between;">
        <div class="card-header">
            <h3 class="mb-0">Édition d'un Pivot</h3>
        </div>
        <div class="card-header">
            <a type="button" class="btn btn-primary" asp-controller="Famille" asp-action="Index">Retour</a>
        </div>
    </div>

    <div class="card-body">
        <!-- Form -->
        <form asp-action="EditPivot" method="post" class="form-row mt-3">
            <div class="col-lg-6 mb-2">
                <label asp-for="Nom" class="control-label">Nom</label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2">
                <label asp-for="Prenom" class="control-label">Prénom</label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2">
                <label asp-for="CIN" class="control-label">CIN</label>
                <input asp-for="CIN" class="form-control" />
                <span asp-validation-for="CIN" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2">
                <label asp-for="DateNaissance" class="control-label">Date de naissance</label>
                <input asp-for="DateNaissance" class="form-control" type="date" />
                <span asp-validation-for="DateNaissance" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2">
                <label asp-for="Adresse" class="control-label">Adresse</label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2">
                <label asp-for="GSM" class="control-label">GSM</label>
                <input asp-for="GSM" class="form-control" />
                <span asp-validation-for="GSM" class="text-danger"></span>
            </div>
            <div class="col-lg-6 mb-2">
                <label asp-for="SecteurId" class="control-label">Secteur</label>
                <select asp-for="SecteurId" class="selectpicker" data-width="100%" data-live-search="true" asp-items="ViewBag.SecteurId">
                    <option value="" selected>--Secteur--</option>
                </select>
                <span asp-validation-for="SecteurId" class="text-danger"></span>
            </div>
            <div class="col-lg-12 mb-2" style="text-align:right;">
                <button type="submit" class="btn btn-outline-info me-2">Enregistrer</button>
            </div>
        </form>
    </div>
</div>